ExternalProject_Add(sdl2
  DOWNLOAD_NO_PROGRESS 1
  URL https://www.libsdl.org/release/SDL2-2.0.8.tar.gz
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/sdl2
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_BINARY_DIR}/sdl2  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
)

set(SDL2_INCLUDE_DIR "${CMAKE_BINARY_DIR}/sdl2/include")
set(SDL2_LIBRARY "${CMAKE_BINARY_DIR}/sdl2/lib/libSDL2main.a" "${CMAKE_BINARY_DIR}/sdl2/lib/libSDL2.a")

include_directories(SYSTEM ${SDL2_INCLUDE_DIR})

set(GAME_DEPENDENCY_LIBRARIES
    ${GAME_DEPENDENCY_LIBRARIES}
    ${SDL2_LIBRARY}
    dl
    )
